#Forces all attachments to be dyeable regardless if this has an effect on the model. This is useful if your server uses custom models for attachments and the models have dyeable elements.
forceDyeableAttachments = false
#The maximum amount of cooldown time remaining before the server will accept another shoot packet from a client. This allows for a litle slack since the server may be lagging.
#Range: 75 ~ 1000
cooldownThreshold = 100

[stun_grenades]
	#After the duration drops to this many ticks, the transparency of the overlay when blinded will gradually fade to 0 alpha.
	#Range: 0 ~ 255
	alphaOverlay = 255
	#Transparency of the overlay when blinded will be this alpha value, before eventually fading to 0 alpha.
	#Range: > 0
	alphaFadeThreshold = 60
	#Volume of most game sounds when deafened will play at this percent, before eventually fading back to %100.
	#Range: 0.0 ~ 1.0
	soundPercentage = 0.1
	#After the duration drops to this many ticks, the ringing volume will gradually fade to 0 and other sound volumes will fade back to %100.
	#Range: > 0
	soundFadeThreshold = 100
	#Volume of the ringing sound when deafened will play at this volume, before eventually fading to 0.
	#Range: 0.0 ~ 1.0
	ringVolume = 0.75

[sounds]
	#The maximum distance weapons can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	gunShotMaxDistance = 128.0
	#The maximum distance rocket explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	rocketExplosionMaxDistance = 128.0
	#The maximum distance pipe grenade explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	pipeGrenadeExplosionMaxDistance = 128.0
	#The maximum distance grenade explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	handGrenadeExplosionMaxDistance = 96.0
	#The maximum distance stun grenade explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	stunGrenadeExplosionMaxDistance = 96.0
	#The maximum distance smoke grenade explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	smokeGrenadeExplosionMaxDistance = 48.0
	#The maximum distance incendiary grenade explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	incendiaryGrenadeExplosionMaxDistance = 64.0
	#The maximum distance molotov explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	molotovExplosionMaxDistance = 64.0
	#The maximum distance reloading can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	reloadMaxDistance = 16.0
	#The maximum distance grenade bouncing can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	grenadeBounceSoundDistance = 24.0
	#The maximum distance impact grenade explosions can be heard by players.
	#Range: 0.0 ~ 1.7976931348623157E308
	impactGrenadeExplosionMaxDistance = 96.0

